### ISSUE TITLE
Erro ao Identar

### ISSUE THREAD

**Issue by EdsonJrVBA** [RonanVico/RVTool#2]
Antes de tudo gostaria de parabenizar pelo exelente trabalho mano!!! Você é o cara!!

COnforme conversado, foi identificado que ao tentar identar a procedure o codigo acaba identando as variaveis da proxima procedure e não da atual....
Reaproveitei a variavel "procedure" eu apenas atribui ela na chamada do codigo para identar as variaveis

[cTOOLS.txt](https://github.com/RonanVico/RVTool/files/4231226/cTOOLS.txt)

**Comment by RonanVico** [comment]
Obrigado , Ajustei ja
