### ISSUE TITLE
Sugestão de Melhoria (Indentar Modulo e correção da indentação do IF 'Sem End If')

### ISSUE THREAD

**Issue by EdsonJrVBA** [RonanVico/RVTool#3]
Ronan, segue sugestão de melhoria referente ao desafio lançado no canal do Marcos.
Criei um Loop para indentar todas as procedures do modulo atual.
Tambem foi corrigido um problema na indentação de IF sem End If ( Exemplo: If 1 = 1 then True)
Identifiquei um problema na identação quando a mais de 1 ElseIf dentro do bloco.. tentei arrumar porem não consegui..
Novamente Obrigado por essa ferramenta maravilhosa mano!! Você é monstro!!!!
[RVTools.zip](https://github.com/RonanVico/RVTool/files/4245219/RVTools.zip)

**Comment by RonanVico** [comment]
Aqui funciona normal o if 1 =1 then true , Não entendi qual , conseguiria postar o antes e depois ?

**Comment by RonanVico** [comment]
Blocos de elseIf Ajustados!
