### ISSUE TITLE
Detector de variáveis não usadas - Range type

### ISSUE THREAD

**Issue by celiasja** [RonanVico/RVTool#5]
Olá, Ronan! Estou passando para deixar a observação abaixo para quando tiver oportunidade de fazer ajustes na ferramenta.

Reparei no seguinte:
Tinha duas variáveis declaradas numa Sub. Uma variável tipo Integer e outra tipo Range. As duas variáveis eram usadas no código, mas depois eu "comentei" as duas linhas onde as variáveis estavam sendo usadas desabbilitando essas duas linhas de código. Depois disso, a função para detectar variáveis não usadas apenas detecta a variável tipo Integer e não a de tipo Range.

Outra nota: as mensagens desta ferramenta ainda não estão traduzidas para inglês. 

Parabéns pelo excelente trabalho e muito obrigada pelo mesmo!

**Comment by RonanVico** [comment]
Olá , Celia , Tudo bom ? 
Obrigado pelo feedback , você conseguiria postar o código com o Integer e o range o qual o Range não foi identificado ?

**Comment by celiasja** [comment]
Oi Ronan.

O c’odigo teria sido qualquer coisa como:

 

Sub Test

Dim i as Integer

Dim rg as Range

 

‘i=1

‘set rg=activesheet.range(“A1:B4”)

 

End Sub

 

Obrigada, 

Celia Alves

**Comment by RonanVico** [comment]
Muito obrigado, consegui ajustar! Bug Fixed ! irei subir a nova versão
