### ISSUE TITLE
RVTOOLS.XLA 

### ISSUE THREAD

**Issue by JCabral2000** [RonanVico/RVTool#7]
Não me está a aparecer a nova funcionalidade.
A versão do rvtools.xla tem três meses, será que não foi atualizada?

**Comment by RonanVico** [comment]
Obrigado por comentar,  eu havia apenas atualizado os Módulos e esqueci de atualizar o .xla , ou seja os novos códigos estavam nos .bas e .cls , Obrigado JCabral , fico grato!
